//! Derives the COMPILED feature set from cargo's own `CARGO_FEATURE_*`
//! exports (the cargo-heal Issue-117 lesson): the set cannot drift from a
//! hand-typed list because nothing hand-types it. `src/build_stamp.rs`
//! compares it against the shipped-release set for the `--version` STALE
//! marker.

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let mut feats: Vec<String> = std::env::vars()
        .filter(|(k, _)| k.starts_with("CARGO_FEATURE_"))
        .map(|(k, _)| {
            k["CARGO_FEATURE_".len()..]
                .to_ascii_lowercase()
                .replace('_', "-")
        })
        .collect();
    feats.sort();
    feats.dedup();
    let list = feats
        .iter()
        .map(|f| format!("    {f:?},"))
        .collect::<Vec<_>>()
        .join("\n");
    let out = format!(
        "/// The COMPILED feature set — generated by build.rs from cargo's own\n\
         /// `CARGO_FEATURE_*` exports; never hand-typed, never drifts.\n\
         pub const COMPILED_FEATURES: &[&str] = &[\n{list}\n];\n"
    );
    let out_dir = std::env::var("OUT_DIR").expect("cargo supplies OUT_DIR");
    std::fs::write(format!("{out_dir}/features.rs"), out).expect("write OUT_DIR/features.rs");
}
