//! The CLM comparison lane (Issue 019; Apache-2.0, not affiliated).
//!
//! Two halves, both pinned to the reference tree at sha `cca045ff`
//! (`Contrastive-LM/CLM`, `src/clm/schema.py` + `server.py`):
//!
//! 1. **The prose-rendering law** ([`to_text`] / [`state_text`] /
//!    [`candidates`]) — "the layout the heads were trained on". Objects
//!    render as `key: value` fields (top-level fields blank-line
//!    separated, nested ones indented), arrays as `- item` lines, key
//!    order preserved. The law is copied BYTE-FOR-BYTE from their Python
//!    (including Python's float `str()` presentation and the trailing
//!    spaces on empty values) — a drift here reads as silent score drift,
//!    never as an error. Every fixture in the tests below is a golden
//!    generated by running THEIR code at the pin (`.raw/clm_goldens.py`,
//!    the offline one-time carve-out — no Python in our tree).
//!
//! 2. **The `/v1/systemone` HTTP adapter** ([`ClmLane`]) — their stack
//!    serves (vLLM Qwen3-8B pooling + `clm-serve` heads), our Rust
//!    measures. Thin localhost HTTP client over std (`serve.rs`'s
//!    hand-rolled posture; no new deps), request built from a
//!    [`DecisionRequest`], response mapped into a
//!    [`DecisionResponse`] with distribution + confidence columns and NO
//!    abstain mapping (CLM has none — the inherited Jev flaw; the wire's
//!    abstain stays first-class for OUR lanes).
//!
//! Deliberate divergences from the reference (each documented where it
//! happens): the wire cannot carry their per-side noul descriptions (a
//! single `criteria: Option<String>` cannot express `{"true": ..,
//! "false": ..}`), so a noul question always uses their default
//! candidates; the choice/score `instructions` fold the optional
//! criteria prose under the prompt; the temperature is pinned at 1.0
//! (their `temperature ∈ (0, 100]` DIVIDES logits — never our τ
//! vocabulary); a noul answer's confidence is not reported by their
//! server, so we compute their own `top − mean(rest)` law over the two
//! probabilities.

use std::collections::HashMap;
use std::io::{Read, Write};
use std::net::TcpStream;
use std::time::{Duration, Instant};

use katgpt_core::decision_wire::{
    Answer, Calibration, DecisionRequest, DecisionResponse, Lane, Outcome, Question,
    QuestionKind, Routing,
};
use serde_json::{json, Map, Value};

/// Their model id for the reference head (`engine.DEFAULT_MODEL`).
pub const DEFAULT_MODEL: &str = "clm-latest";
/// The answer-order law for a noul question: `false` FIRST (`NOUL_KEYS`).
pub const NOUL_KEYS: [&str; 2] = ["false", "true"];
/// The env var naming the `clm-serve` base URL (Issue 019).
pub const SERVE_URL_ENV: &str = "CLM_SERVE_URL";
/// The default posture: localhost, their `clm-serve` port 8700.
pub const DEFAULT_SERVE_URL: &str = "http://127.0.0.1:8700";

// ─────────────────────────────────────────────────────────────── the law

/// Their `to_text` (`schema.py`): a state / description that may be a
/// string, object or array rendered as plain text — the heads are trained
/// on prose, not on JSON.
pub fn to_text(x: &Value) -> String {
    to_text_indent(x, 0)
}

fn to_text_indent(x: &Value, indent: usize) -> String {
    match x {
        // None → ""; str → as-is.
        Value::Null => String::new(),
        Value::String(s) => s.clone(),
        // bool BEFORE number (Python's isinstance order; disjoint in Rust).
        Value::Bool(b) => if *b { "true" } else { "false" }.to_string(),
        Value::Number(n) => render_number(n),
        Value::Object(map) => {
            let pad = " ".repeat(indent);
            let parts: Vec<String> = map
                .iter()
                .map(|(k, v)| match container(v) {
                    // Non-empty containers break onto their own indented block.
                    Some(true) => format!("{pad}{k}:\n{}", to_text_indent(v, indent + 2)),
                    _ => format!("{pad}{k}: {}", to_text_indent(v, 0)),
                })
                .collect();
            // Top-level fields blank-line separated; nested ones single-newline.
            if indent == 0 { parts.join("\n\n") } else { parts.join("\n") }
        }
        Value::Array(items) => {
            let pad = " ".repeat(indent);
            let parts: Vec<String> = items
                .iter()
                .map(|v| match container(v) {
                    Some(true) => format!("{pad}-\n{}", to_text_indent(v, indent + 2)),
                    _ => format!("{pad}- {}", to_text_indent(v, 0)),
                })
                .collect();
            parts.join("\n")
        }
    }
}

/// `Some(non_empty)` when `v` is a dict/list — their `isinstance(v, (dict,
/// list)) and v` branch; `None` for scalars. The emptiness decides whether
/// a value renders as `key: value` / `- item` or breaks onto a block.
fn container(v: &Value) -> Option<bool> {
    match v {
        Value::Object(m) => Some(!m.is_empty()),
        Value::Array(a) => Some(!a.is_empty()),
        _ => None,
    }
}

/// Their `str(x)` over a JSON number. Integers are positional; floats get
/// Python's `repr` presentation (shortest round-trip digits, `.0` on
/// integral values, exponential outside `[1e-4, 1e16)` with a signed
/// two-digit exponent).
fn render_number(n: &serde_json::Number) -> String {
    if let Some(i) = n.as_i64() {
        return i.to_string();
    }
    if let Some(u) = n.as_u64() {
        return u.to_string();
    }
    if let Some(i) = n.as_i128() {
        return i.to_string();
    }
    if let Some(u) = n.as_u128() {
        return u.to_string();
    }
    match n.as_f64() {
        Some(f) => py_float(f),
        // serde_json can no longer represent it — their Python would keep
        // arbitrary precision; we render the raw text form as the least
        // surprising fallback.
        None => n.to_string(),
    }
}

/// Python `repr(float)`: shortest round-trip digits, then the presentation
/// rule (`-4 <= adj < 16` fixed, else exponential `d[.ddd]e±XX`).
fn py_float(v: f64) -> String {
    if v.is_nan() {
        return "nan".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 { "inf" } else { "-inf" }.to_string();
    }
    // Rust's LowerExp gives the shortest round-trip digits: `d[.ddd]e<exp>`.
    let sci = format!("{:e}", v);
    let (mantissa, exp) = sci.split_once('e').unwrap_or((sci.as_str(), "0"));
    let adj: i32 = exp.parse().unwrap_or(0);
    let (neg, mantissa) = match mantissa.strip_prefix('-') {
        Some(m) => (true, m),
        None => (false, mantissa),
    };
    let digits: String = mantissa.chars().filter(|c| *c != '.').collect();
    // `adj` = floor(log10(|v|)) = the exponent of the leading digit.
    let body = if adj >= 0 {
        // Fixed notation (adj < 16, Python's rule): decimal point after
        // adj+1 digits, right-padded when the digits stop short (1e15).
        if adj < 16 {
            let point = (adj + 1) as usize;
            let mut int_part: String = digits.chars().take(point).collect();
            let frac_part: String = digits.chars().skip(point).collect();
            while int_part.len() < point {
                int_part.push('0');
            }
            if frac_part.is_empty() {
                format!("{int_part}.0")
            } else {
                format!("{int_part}.{frac_part}")
            }
        } else {
            exponential(&digits, adj)
        }
    } else if adj >= -4 {
        // Sub-unity fixed notation: `0.` + the zeros the exponent implies
        // + the digits (1e-4 → 0.0001).
        format!("0.{}{}", "0".repeat((-adj - 1) as usize), digits)
    } else {
        exponential(&digits, adj)
    };
    if neg { format!("-{body}") } else { body }
}

/// The exponential branch: `d[.ddd]e±XX` (sign always, exponent ≥ 2 digits).
fn exponential(digits: &str, adj: i32) -> String {
    let mant = if digits.len() == 1 {
        digits.to_string()
    } else {
        format!("{}.{}", &digits[..1], &digits[1..])
    };
    format!("{mant}e{}{:02}", if adj < 0 { '-' } else { '+' }, adj.abs())
}

/// Their `state_text`: context first, question last, blank-line separated;
/// the shorter side survives alone; both stripped.
pub fn state_text(state: &Value, instructions: &Value) -> String {
    let s = to_text(state);
    let s = s.trim();
    let i = to_text(instructions);
    let i = i.trim();
    if !s.is_empty() && !i.is_empty() {
        format!("{s}\n\n{i}")
    } else {
        format!("{s}{i}")
    }
}

/// `(option keys in answer order, candidate text per option)` for one of
/// OUR questions — their `candidates()` law applied at the adapter seam.
///
/// * `noul`: keys `["false", "true"]` (false FIRST — the answer order the
///   distribution maps onto). Our wire cannot carry their per-side
///   descriptions, so the default law always applies: `"No. This is
///   false: {instructions}"` / `"Yes. This is true: {instructions}"`,
///   or the bare key when the prompt is empty.
/// * `choice`: keys are the option POSITIONS (`"0"`, `"1"`, … — the
///   answer's index maps straight back to [`Outcome::Choice`]); the
///   candidate text is the option's own text, or the key when the option
///   is empty (their `crit[k] in (None, "")` law — "nothing is prefixed,
///   so a candidate reaches the encoder exactly as the caller wrote it").
/// * `score`: keys are the level positions; the text is each rubric level.
pub fn candidates(q: &Question) -> (Vec<String>, Vec<String>) {
    let ins = q.prompt.trim().to_string();
    match q.kind {
        QuestionKind::Noul => {
            let texts = if ins.is_empty() {
                NOUL_KEYS.iter().map(|k| format!("{k}: {k}")).collect()
            } else {
                vec![
                    format!("false: No. This is false: {ins}"),
                    format!("true: Yes. This is true: {ins}"),
                ]
            };
            (NOUL_KEYS.iter().map(|k| k.to_string()).collect(), texts)
        }
        QuestionKind::Choice | QuestionKind::Score => {
            let keys: Vec<String> = (0..q.options.len()).map(|i| i.to_string()).collect();
            let texts = q
                .options
                .iter()
                .enumerate()
                .map(|(i, o)| {
                    if o.is_empty() {
                        i.to_string()
                    } else {
                        o.clone()
                    }
                })
                .collect();
            (keys, texts)
        }
    }
}

/// The `instructions` the request carries for one question: the prompt,
/// with the optional criteria prose folded under it (single newline — the
/// blank-line law separates CONTEXT from QUESTION at [`state_text`]'s
/// level; prompt and criteria are one logical question here).
fn instructions_of(q: &Question) -> String {
    match &q.criteria {
        Some(c) if !c.trim().is_empty() => format!("{}\n{}", q.prompt, c),
        _ => q.prompt.clone(),
    }
}

// ─────────────────────────────────────────────────────── the request wire

/// Build their `POST /v1/systemone` body from a [`DecisionRequest`].
///
/// `{"state": .., "model": "clm-latest", "questions": {id: {type,
/// instructions, criteria?}}, "temperature": 1.0}` — the TypeSafe shape
/// their `schema.py` docstring pins. `serde_json` runs with
/// `preserve_order`, so a choice's `criteria` object keeps OUR option
/// order — the order their `list(crit)` reads, and the order the answer
/// distribution maps back onto (parity-critical).
pub fn build_body(req: &DecisionRequest) -> Value {
    let mut questions = Map::new();
    for q in &req.questions {
        let mut qj = Map::new();
        qj.insert("type".into(), json!(q.kind.as_str()));
        qj.insert("instructions".into(), json!(instructions_of(q)));
        match q.kind {
            // No criteria: their `crit or {}` default-candidates law applies.
            QuestionKind::Noul => {}
            QuestionKind::Choice => {
                let mut criteria = Map::new();
                for (i, o) in q.options.iter().enumerate() {
                    criteria.insert(i.to_string(), json!(o));
                }
                qj.insert("criteria".into(), Value::Object(criteria));
            }
            QuestionKind::Score => {
                qj.insert("criteria".into(), json!(q.options));
            }
        }
        questions.insert(q.id.clone(), Value::Object(qj));
    }
    json!({
        "state": req.state,
        "model": DEFAULT_MODEL,
        "questions": Value::Object(questions),
        "temperature": 1.0,
    })
}

// ────────────────────────────────────────────────────── the response wire

/// A mapping failure — fail-closed, never a guessed answer.
#[derive(Debug, Clone, PartialEq)]
pub struct ClmError(pub String);

impl std::fmt::Display for ClmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "clm lane: {}", self.0)
    }
}

impl std::error::Error for ClmError {}

fn err<T>(msg: impl Into<String>) -> Result<T, ClmError> {
    Err(ClmError(msg.into()))
}

/// Their `confidence()` law: top probability minus the mean of the rest,
/// clamped to `[0, 1]`. Used for a noul answer's confidence (their server
/// does not report one) and as the fallback recomputation for the others.
pub fn confidence(probs: &[f32]) -> f32 {
    if probs.len() < 2 {
        return 1.0;
    }
    let j = probs
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.total_cmp(b.1))
        .map(|(i, _)| i)
        .unwrap_or(0);
    let mut rest = Vec::with_capacity(probs.len() - 1);
    for (i, p) in probs.iter().enumerate() {
        if i != j {
            rest.push(*p);
        }
    }
    let mean = rest.iter().sum::<f32>() / rest.len() as f32;
    (probs[j] - mean).clamp(0.0, 1.0)
}

/// Map their `{"model", "answers": {id: Answer}, "usage"}` body into a
/// [`DecisionResponse`] for `req`, then fail-closed-validate the pair.
///
/// * noul: `{"noul": p_true}` → one probability, `yes = p >= 0.5` (their
///   `label_of` threshold), confidence recomputed by their own law.
/// * choice: `probabilities` in THEIR key order — which is OUR option
///   order by construction (`build_body`'s preserve-order law); a key
///   order drift is an error, never a silent misalignment. Confidence as
///   reported (validated finite + in range).
/// * score: probabilities in level order; the recorded level is their
///   `label_of` argmax.
pub fn map_response(req: &DecisionRequest, body: &Value) -> Result<DecisionResponse, ClmError> {
    let answers = body
        .get("answers")
        .and_then(Value::as_object)
        .ok_or_else(|| ClmError("response has no answers object".into()))?;
    let mut out = Vec::with_capacity(req.questions.len());
    for q in &req.questions {
        let a = answers
            .get(&q.id)
            .ok_or_else(|| ClmError(format!("response missing answer for question {}", q.id)))?;
        let answer = match q.kind {
            QuestionKind::Noul => {
                let p = a
                    .get("noul")
                    .and_then(Value::as_f64)
                    .ok_or_else(|| ClmError(format!("noul answer {} missing `noul`", q.id)))?;
                let p = p as f32;
                if !(0.0..=1.0).contains(&p) {
                    return err(format!("noul answer {} probability {p} outside [0, 1]", q.id));
                }
                Answer {
                    question_id: q.id.clone(),
                    outcome: Some(Outcome::Noul { yes: p >= 0.5 }),
                    probabilities: vec![p],
                    confidence: confidence(&[1.0 - p, p]),
                }
            }
            QuestionKind::Choice | QuestionKind::Score => {
                let dist = a
                    .get("probabilities")
                    .and_then(Value::as_object)
                    .ok_or_else(|| {
                        ClmError(format!("answer {} missing probabilities object", q.id))
                    })?;
                let (keys, _texts) = candidates(q);
                if dist.len() != keys.len() {
                    return err(format!(
                        "answer {} has {} probabilities for {} options",
                        q.id,
                        dist.len(),
                        keys.len()
                    ));
                }
                // THEIR key order is OUR option order — drift is an error.
                let mut probs = Vec::with_capacity(keys.len());
                for key in &keys {
                    let p = dist.get(key).and_then(Value::as_f64).ok_or_else(|| {
                        ClmError(format!("answer {} key {key} missing/misordered", q.id))
                    })?;
                    let p = p as f32;
                    if !(0.0..=1.0).contains(&p) {
                        return err(format!("answer {} probability {p} outside [0, 1]", q.id));
                    }
                    probs.push(p);
                }
                let confidence = match a.get("confidence").and_then(Value::as_f64) {
                    Some(c) => {
                        let c = c as f32;
                        if !c.is_finite() || !(0.0..=1.0).contains(&c) {
                            return err(format!("answer {} confidence {c} outside [0, 1]", q.id));
                        }
                        c
                    }
                    None => confidence(&probs),
                };
                let top = probs
                    .iter()
                    .enumerate()
                    .max_by(|x, y| x.1.total_cmp(y.1))
                    .map(|(i, _)| i)
                    .unwrap_or(0) as u32;
                let outcome = match q.kind {
                    QuestionKind::Choice => Outcome::Choice { index: top },
                    _ => Outcome::Score { level: top },
                };
                Answer {
                    question_id: q.id.clone(),
                    outcome: Some(outcome),
                    probabilities: probs,
                    confidence,
                }
            }
        };
        out.push(answer);
    }
    let response = DecisionResponse {
        answers: out,
        routing: Routing {
            lane: Lane::Clm,
            reason: Some(format!("external comparison lane ({DEFAULT_MODEL} over /v1/systemone)")),
        },
        calibration: Calibration::none(),
    };
    response
        .validate_against(req)
        .map_err(|e| ClmError(format!("mapped response fails the wire contract: {e}")))?;
    Ok(response)
}

// ────────────────────────────────────────────────── the lane

/// One parsed HTTP/1.1 reply: `(status, lowercased headers, body bytes)`.
type HttpReply = (u16, HashMap<String, String>, Vec<u8>);

/// Per-decision measurement record (Issue 019: "record latency +
/// `usage.input_tokens`").
#[derive(Debug, Clone, PartialEq)]
pub struct ClmUsage {
    /// Their `usage.input_tokens` (embedding tokens billed).
    pub input_tokens: u64,
    /// Client round-trip wall ms (the cross-lane consistency measure).
    pub client_ms: f64,
    /// Their server-side latency from the `X-CLM-Latency-Ms` header.
    pub server_ms: Option<f64>,
}

/// The CLM comparison lane: a thin localhost HTTP client to their
/// `clm-serve`. std-only (the `serve.rs` hand-rolled HTTP posture) —
/// their stack serves, our Rust measures.
#[derive(Debug, Clone)]
pub struct ClmLane {
    host: String,
    port: u16,
    /// Always `/v1/systemone` today; a field so the stub tests can pin it.
    path: String,
    timeout: Duration,
}

impl Default for ClmLane {
    fn default() -> Self {
        Self::from_url(&std::env::var(SERVE_URL_ENV).unwrap_or_else(|_| DEFAULT_SERVE_URL.into()))
    }
}

impl ClmLane {
    /// Parse an `http://host:port` base URL (loopback-only posture — their
    /// server runs beside the harness on the same box).
    pub fn from_url(url: &str) -> Self {
        let rest = url
            .strip_prefix("http://")
            .unwrap_or_else(|| url.strip_prefix("https://").unwrap_or(url));
        let (authority, path) = match rest.split_once('/') {
            Some((a, p)) => (a, format!("/{p}")),
            None => (rest, "/v1/systemone".to_string()),
        };
        let (host, port) = match authority.rsplit_once(':') {
            Some((h, p)) => (h.to_string(), p.parse().unwrap_or(8700)),
            None => (authority.to_string(), 80),
        };
        Self {
            host,
            port,
            path: if path == "/" { "/v1/systemone".into() } else { path },
            timeout: Duration::from_secs(120),
        }
    }

    /// One decision round: build the wire body from `req`, POST it, map
    /// the answers back. Returns the response plus the usage record.
    pub fn decide(&self, req: &DecisionRequest) -> Result<(DecisionResponse, ClmUsage), ClmError> {
        let body = build_body(req).to_string();
        let t0 = Instant::now();
        let (status, headers, body) = self.post(body.as_bytes())?;
        let client_ms = t0.elapsed().as_secs_f64() * 1000.0;
        if status != 200 {
            return err(format!(
                "POST {} -> HTTP {status}: {}",
                self.path,
                String::from_utf8_lossy(&body)
            ));
        }
        let server_ms = headers
            .get("x-clm-latency-ms")
            .and_then(|v| v.trim().parse::<f64>().ok());
        let parsed: Value = serde_json::from_slice(&body)
            .map_err(|e| ClmError(format!("response is not JSON: {e}")))?;
        let input_tokens = parsed
            .pointer("/usage/input_tokens")
            .and_then(Value::as_u64)
            .ok_or_else(|| ClmError("response missing usage.input_tokens".into()))?;
        Ok((
            map_response(req, &parsed)?,
            ClmUsage {
                input_tokens,
                client_ms,
                server_ms,
            },
        ))
    }

    /// The hand-rolled HTTP/1.1 POST (`Connection: close`), mirroring
    /// `serve.rs`'s min-envelope posture from the client side.
    fn post(&self, body: &[u8]) -> Result<HttpReply, ClmError> {
        let mut stream = TcpStream::connect((self.host.as_str(), self.port))
            .map_err(|e| ClmError(format!("connect {}:{}: {e}", self.host, self.port)))?;
        stream
            .set_read_timeout(Some(self.timeout))
            .and_then(|_| stream.set_write_timeout(Some(self.timeout)))
            .map_err(|e| ClmError(format!("set timeout: {e}")))?;
        let head = format!(
            "POST {} HTTP/1.1\r\nHost: {}:{}\r\nContent-Type: application/json\r\n\
             Content-Length: {}\r\nConnection: close\r\n\r\n",
            self.path,
            self.host,
            self.port,
            body.len()
        );
        stream
            .write_all(head.as_bytes())
            .and_then(|_| stream.write_all(body))
            .and_then(|_| stream.flush())
            .map_err(|e| ClmError(format!("write: {e}")))?;
        let mut raw = Vec::new();
        stream
            .read_to_end(&mut raw)
            .map_err(|e| ClmError(format!("read: {e}")))?;
        parse_http_response(&raw)
    }
}

/// Split a raw HTTP/1.1 response into `(status, lowercased-headers, body)`.
fn parse_http_response(raw: &[u8]) -> Result<HttpReply, ClmError> {
    let text = String::from_utf8_lossy(raw);
    let (head, body) = text
        .split_once("\r\n\r\n")
        .ok_or_else(|| ClmError("response has no header/body separator".into()))?;
    let mut lines = head.split("\r\n");
    let status_line = lines.next().unwrap_or_default();
    let status: u16 = status_line
        .split_whitespace()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .ok_or_else(|| ClmError(format!("malformed status line: {status_line}")))?;
    let mut headers = HashMap::new();
    for line in lines {
        if let Some((k, v)) = line.split_once(':') {
            headers.insert(k.trim().to_ascii_lowercase(), v.trim().to_string());
        }
    }
    let mut body_bytes = body.as_bytes().to_vec();
    if let Some(len) = headers.get("content-length").and_then(|v| v.parse::<usize>().ok()) {
        body_bytes.truncate(len);
    }
    Ok((status, headers, body_bytes))
}

// ───────────────────────────────────────────────────────────────── tests

#[cfg(test)]
mod tests {
    use super::*;
    use katgpt_core::decision_wire::Question;

    fn obj(pairs: &[(&str, Value)]) -> Value {
        let mut m = Map::new();
        for (k, v) in pairs {
            m.insert((*k).to_string(), v.clone());
        }
        Value::Object(m)
    }

    fn s(v: &str) -> Value {
        Value::String(v.to_string())
    }

    /// The goldens: every expectation below was produced by running THEIR
    /// `schema.py` at the pinned sha `cca045ff` (`.raw/clm_goldens.py`,
    /// the offline one-time carve-out). A diff here is a law break, never
    /// a formatting preference.
    #[test]
    fn to_text_matches_the_reference_goldens() {
        let cases: Vec<(&str, Value, &str)> = vec![
            ("null", Value::Null, ""),
            ("str", s("hello"), "hello"),
            ("empty_str", s(""), ""),
            ("bool_true", Value::Bool(true), "true"),
            ("bool_false", Value::Bool(false), "false"),
            ("int", json!(42), "42"),
            ("int_neg", json!(-7), "-7"),
            ("float", serde_json::from_str::<Value>("3.14").unwrap(), "3.14"),
            ("float_integral", json!(1.0), "1.0"),
            ("float_zero", json!(0.0), "0.0"),
            ("float_neg_zero", json!(-0.0), "-0.0"),
            ("float_big", json!(1e20), "1e+20"),
            ("float_1e16", json!(1e16), "1e+16"),
            ("float_1e15", json!(1e15), "1000000000000000.0"),
            ("float_small", json!(0.0001), "0.0001"),
            ("float_smaller", json!(0.00001), "1e-05"),
            ("float_tiny", json!(1.5e-7), "1.5e-07"),
            ("float_pi_long", json!(0.1 + 0.2), "0.30000000000000004"),
            ("empty_dict", json!({}), ""),
            ("empty_list", json!([]), ""),
            ("flat_obj", obj(&[("a", json!(1)), ("b", s("x"))]), "a: 1\n\nb: x"),
            (
                "nested_obj",
                obj(&[
                    ("user", obj(&[("name", s("Bo")), ("tags", json!(["a", "b"]))])),
                    ("n", json!(3)),
                ]),
                "user:\n  name: Bo\n  tags:\n    - a\n    - b\n\nn: 3",
            ),
            (
                "list_of_objects",
                json!([{"k": 1}, {"k": 2}]),
                "-\n  k: 1\n-\n  k: 2",
            ),
            ("empty_containers", obj(&[("e", json!({})), ("f", json!([]))]), "e: \n\nf: "),
            (
                "unicode",
                obj(&[("name", s("café")), ("city", s("กรุงเทพ"))]),
                "name: café\n\ncity: กรุงเทพ",
            ),
            (
                "deep",
                obj(&[("a", obj(&[("b", obj(&[("c", json!(["x", "y"]))]))]))]),
                "a:\n  b:\n    c:\n      - x\n      - y",
            ),
            (
                "list_mixed",
                json!(["plain", {"k": 1}, 42, Value::Null]),
                "- plain\n-\n  k: 1\n- 42\n- ",
            ),
            (
                "bool_in_obj",
                obj(&[("ok", Value::Bool(true)), ("n", Value::Bool(false))]),
                "ok: true\n\nn: false",
            ),
            (
                "nested_list_in_list",
                json!([["x", "y"], ["z"]]),
                "-\n  - x\n  - y\n-\n  - z",
            ),
        ];
        for (name, input, want) in cases {
            let got = to_text(&input);
            assert_eq!(got, want, "to_text golden `{name}` drifted from the reference");
        }
    }

    #[test]
    fn state_text_matches_the_reference_goldens() {
        let cases: Vec<(&str, Value, Value, &str)> = vec![
            ("both", obj(&[("t", s("ctx"))]), s("Is it fine?"), "t: ctx\n\nIs it fine?"),
            ("str_both", s("plain context"), s("Is it fine?"), "plain context\n\nIs it fine?"),
            ("empty_state", Value::Null, s("Only the question"), "Only the question"),
            ("empty_ins", s("Only the context"), s(""), "Only the context"),
            ("both_empty", s(""), s(""), ""),
            (
                "ws_strip",
                s("  padded context  \n"),
                s("\n  padded question  "),
                "padded context\n\npadded question",
            ),
        ];
        for (name, st, ins, want) in cases {
            let got = state_text(&st, &ins);
            assert_eq!(got, want, "state_text golden `{name}` drifted from the reference");
        }
    }

    fn noul(id: &str, prompt: &str) -> Question {
        Question::noul(id, prompt)
    }

    fn choice(id: &str, options: &[&str]) -> Question {
        Question::choice(
            id,
            "pick",
            options.iter().map(|o| (*o).to_string()).collect(),
            None,
        )
    }

    fn score(id: &str, levels: &[&str]) -> Question {
        Question::score(id, "rate", levels.iter().map(|o| (*o).to_string()).collect())
    }

    #[test]
    fn candidates_match_the_reference_goldens() {
        // noul default law, both prompt states.
        let (keys, texts) = candidates(&noul("q", "Is the sky blue?"));
        assert_eq!(keys, ["false", "true"]);
        assert_eq!(
            texts,
            [
                "false: No. This is false: Is the sky blue?",
                "true: Yes. This is true: Is the sky blue?"
            ]
        );
        let (keys, texts) = candidates(&noul("q", ""));
        assert_eq!(keys, ["false", "true"]);
        assert_eq!(texts, ["false: false", "true: true"]);
        // choice: empty option → its key (their `crit[k] in (None, "")`
        // law; the golden carries {"move": "walk left", "jump": "",
        // "stay": None}).
        let (keys, texts) = candidates(&choice("q", &["walk left", "", "stay"]));
        assert_eq!(keys, ["0", "1", "2"]);
        // Only the EMPTY option falls back to its key; non-empty text stays
        // verbatim (their golden: {"move": "walk left", "jump": "",
        // "stay": None} → ["walk left", "jump", "stay"]).
        assert_eq!(texts, ["walk left", "1", "stay"]);
        // score: positional keys, levels verbatim.
        let (keys, texts) = candidates(&score("q", &["bad", "meh", "great"]));
        assert_eq!(keys, ["0", "1", "2"]);
        assert_eq!(texts, ["bad", "meh", "great"]);
    }

    #[test]
    fn build_body_matches_the_composite_golden_and_keeps_option_order() {
        // The golden `pairs` case, replayed through the adapter: the state
        // renders `ticket: 4711\n\nsys: safari` + the question; the choice
        // criteria carry positions 0/1 in OUR order.
        let req = DecisionRequest {
            state: obj(&[("ticket", s("4711")), ("sys", s("safari"))]).to_string(),
            questions: vec![
                Question::choice(
                    "q1",
                    "Which subsystem?",
                    vec!["auth".into(), "session".into()],
                    None,
                ),
                noul("q2", "Reproducible?"),
            ],
        };
        let body = build_body(&req);
        assert_eq!(body["state"], req.state);
        assert_eq!(body["model"], DEFAULT_MODEL);
        assert_eq!(body["temperature"], json!(1.0));
        let q1 = &body["questions"]["q1"];
        assert_eq!(q1["type"], "choice");
        assert_eq!(q1["instructions"], "Which subsystem?");
        // preserve_order: the serialized criteria object must read
        // "0" then "1" — their `list(crit)` order IS the answer order.
        let criteria_text = q1["criteria"].to_string();
        let zero = criteria_text.find("\"0\"").expect("key 0 present");
        let one = criteria_text.find("\"1\"").expect("key 1 present");
        assert!(zero < one, "criteria order drifted: {criteria_text}");
        assert_eq!(q1["criteria"]["0"], "auth");
        assert_eq!(q1["criteria"]["1"], "session");
        let q2 = &body["questions"]["q2"];
        assert_eq!(q2["type"], "noul");
        assert!(
            q2.get("criteria").is_none(),
            "noul carries no criteria — their default law applies"
        );
    }

    #[test]
    fn noul_instructions_fold_the_criteria_prose() {
        let mut q = noul("q", "Severity of the report?");
        q.criteria = Some("Use the scale from the runbook".into());
        assert_eq!(
            instructions_of(&q),
            "Severity of the report?\nUse the scale from the runbook"
        );
        q.criteria = Some("   ".into());
        assert_eq!(instructions_of(&q), "Severity of the report?");
    }

    fn golden_response_body() -> Value {
        json!({
            "model": DEFAULT_MODEL,
            "answers": {
                "c1": {"type": "choice", "choice": "1", "confidence": 0.5,
                        "probabilities": {"0": 0.25, "1": 0.5, "2": 0.25}},
                "n1": {"type": "noul", "noul": 0.875},
                "s1": {"type": "score", "score": 2.5, "confidence": 0.75,
                        "legend": {"0": "low", "1": "mid", "2": "high", "3": "extreme"},
                        "probabilities": {"0": 0.125, "1": 0.125, "2": 0.25, "3": 0.5}},
            },
            "usage": {"billing_units": 3, "input_tokens": 128, "output_tokens": 0},
        })
    }

    fn golden_request() -> DecisionRequest {
        DecisionRequest {
            state: "ticket 4711: login loop".into(),
            questions: vec![
                choice("c1", &["auth", "session", "transport"]),
                noul("n1", "Reproducible?"),
                score("s1", &["low", "mid", "high", "extreme"]),
            ],
        }
    }

    #[test]
    fn map_response_matches_the_wire_and_validates() {
        let req = golden_request();
        let resp = map_response(&req, &golden_response_body()).expect("golden body maps");
        assert_eq!(resp.routing.lane, Lane::Clm);
        assert_eq!(resp.calibration, Calibration::none());
        let a = &resp.answers[0];
        assert_eq!(a.outcome, Some(Outcome::Choice { index: 1 }));
        assert_eq!(a.probabilities, vec![0.25, 0.5, 0.25]);
        assert_eq!(a.confidence, 0.5);
        let n = &resp.answers[1];
        assert_eq!(n.outcome, Some(Outcome::Noul { yes: true }));
        assert_eq!(n.probabilities, vec![0.875]);
        // Their law over [0.125, 0.875]: top − mean(rest) = 0.75.
        assert!((n.confidence - 0.75).abs() < 1e-6);
        let sc = &resp.answers[2];
        assert_eq!(sc.outcome, Some(Outcome::Score { level: 3 }));
        assert_eq!(sc.probabilities, vec![0.125, 0.125, 0.25, 0.5]);
        assert_eq!(sc.confidence, 0.75);
        resp.validate_against(&req).expect("mapped pair validates");
    }

    #[test]
    fn map_response_maps_by_key_name_so_json_order_cannot_misalign() {
        let req = golden_request();
        let mut body = golden_response_body();
        // A server that serializes the distribution's keys in a different
        // ORDER still maps correctly — the NAME is the semantics; we look
        // up by name, so JSON order can never misalign an option.
        body["answers"]["c1"]["probabilities"] = json!({"2": 0.25, "1": 0.5, "0": 0.25});
        let resp = map_response(&req, &body).expect("reordered keys still map by name");
        assert_eq!(resp.answers[0].probabilities, vec![0.25, 0.5, 0.25]);
    }

    #[test]
    fn map_response_fails_closed_on_missing_answer_or_bad_range() {
        let req = golden_request();
        let mut body = golden_response_body();
        body["answers"]["n1"]["noul"] = json!(1.5);
        assert!(map_response(&req, &body).is_err(), "p > 1 must fail");
        let mut body = golden_response_body();
        body["answers"].as_object_mut().unwrap().remove("s1");
        assert!(map_response(&req, &body).is_err(), "missing answer must fail");
    }

    #[test]
    fn confidence_follows_their_law() {
        assert!((confidence(&[0.5, 0.5]) - 0.0).abs() < 1e-6);
        assert!((confidence(&[0.9, 0.1]) - 0.8).abs() < 1e-6);
        assert!((confidence(&[0.25, 0.25, 0.25, 0.25]) - 0.0).abs() < 1e-6);
        // top 0.5, rest mean 1/6 → 1/3.
        assert!((confidence(&[0.5, 1.0 / 6.0, 1.0 / 6.0, 1.0 / 6.0]) - 1.0 / 3.0).abs() < 1e-5);
        assert_eq!(confidence(&[1.0]), 1.0);
    }

    #[test]
    fn from_url_parses_the_documented_postures() {
        let lane = ClmLane::from_url("http://127.0.0.1:8700");
        assert_eq!(
            (lane.host.as_str(), lane.port, lane.path.as_str()),
            ("127.0.0.1", 8700, "/v1/systemone")
        );
        let lane = ClmLane::from_url("http://clm.box:9000");
        assert_eq!((lane.host.as_str(), lane.port), ("clm.box", 9000));
        let lane = ClmLane::from_url("127.0.0.1:8700");
        assert_eq!(
            (lane.host.as_str(), lane.port, lane.path.as_str()),
            ("127.0.0.1", 8700, "/v1/systemone")
        );
    }

    /// T2(b) — the stub-HTTP wire-shape mapping test: a local listener
    /// answers ONE canned `/v1/systemone` response; the lane must send
    /// the documented request wire (method, path, JSON body shape, option
    /// order) and map the answers back. Wire shape, not scores — the
    /// determinism pin lives at T3 where a real server exists.
    #[test]
    fn stub_http_round_trip_pins_the_request_wire() {
        use std::io::BufRead;
        let listener = std::net::TcpListener::bind(("127.0.0.1", 0)).expect("ephemeral bind");
        let port = listener.local_addr().unwrap().port();
        let handle = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            let mut reader = std::io::BufReader::new(stream.try_clone().expect("clone"));
            let mut request_line = String::new();
            reader.read_line(&mut request_line).expect("request line");
            assert!(
                request_line.starts_with("POST /v1/systemone HTTP/1.1"),
                "unexpected request line: {request_line}"
            );
            let mut content_length = 0usize;
            loop {
                let mut line = String::new();
                reader.read_line(&mut line).expect("header line");
                let line = line.trim_end();
                if line.is_empty() {
                    break;
                }
                match line.split_once(':') {
                    Some((k, v)) if k.eq_ignore_ascii_case("content-length") => {
                        content_length = v.trim().parse().unwrap_or(0);
                    }
                    _ => {}
                }
            }
            let mut body = vec![0u8; content_length];
            reader.read_exact(&mut body).expect("body");
            let body: Value = serde_json::from_slice(&body).expect("body JSON");
            // The wire shape, asserted at the server side:
            assert_eq!(body["model"], DEFAULT_MODEL);
            assert_eq!(body["temperature"], json!(1.0));
            assert_eq!(body["state"], "fixture state");
            let q = &body["questions"]["pick"];
            assert_eq!(q["type"], "choice");
            assert_eq!(q["instructions"], "pick one");
            assert_eq!(q["criteria"]["0"], "left");
            assert_eq!(q["criteria"]["1"], "right");
            let response = json!({
                "model": DEFAULT_MODEL,
                "answers": {
                    "pick": {"type": "choice", "choice": "1", "confidence": 0.5,
                              "probabilities": {"0": 0.25, "1": 0.75}},
                },
                "usage": {"billing_units": 1, "input_tokens": 128, "output_tokens": 0},
            })
            .to_string();
            drop(reader);
            let mut stream = stream;
            stream
                .write_all(
                    format!(
                        "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\
                         Content-Length: {}\r\nX-CLM-Latency-Ms: 12.5\r\nConnection: close\r\n\r\n{response}",
                        response.len()
                    )
                    .as_bytes(),
                )
                .expect("respond");
        });

        let lane = ClmLane::from_url(&format!("http://127.0.0.1:{port}"));
        let mut req = DecisionRequest {
            state: "fixture state".into(),
            questions: vec![choice("pick", &["left", "right"])],
        };
        req.questions[0].prompt = "pick one".into();
        let (resp, usage) = lane.decide(&req).expect("round trip");
        handle.join().expect("server thread");
        assert_eq!(resp.answers.len(), 1);
        assert_eq!(resp.answers[0].outcome, Some(Outcome::Choice { index: 1 }));
        assert_eq!(usage.input_tokens, 128);
        assert_eq!(usage.server_ms, Some(12.5));
        assert!(usage.client_ms >= 0.0);
    }

    #[test]
    fn lane_refuses_a_non_200_loudly() {
        use std::io::BufRead;
        let listener = std::net::TcpListener::bind(("127.0.0.1", 0)).expect("bind");
        let port = listener.local_addr().unwrap().port();
        std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            // Drain the request BEFORE responding: closing with unread
            // request bytes in flight sends a TCP RST that kills the
            // client's read (os error 54) instead of delivering the 422.
            let mut reader = std::io::BufReader::new(&stream);
            let mut line = String::new();
            loop {
                line.clear();
                reader.read_line(&mut line).expect("read");
                if line.trim_end().is_empty() {
                    break;
                }
            }
            let mut stream = stream;
            stream
                .write_all(
                    b"HTTP/1.1 422 Unprocessable Entity\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
                )
                .expect("respond");
        });
        let lane = ClmLane::from_url(&format!("http://127.0.0.1:{port}"));
        let err = lane.decide(&golden_request()).expect_err("422 must be loud");
        assert!(err.0.contains("422"), "unexpected error: {err}");
    }
}
