//! The `--version` build stamp (the cargo-heal Issue-117 shape): a binary
//! whose compiled feature set is incomplete against the shipped release set
//! says so LOUDLY, next to the exact rebuild command — one command, from any
//! terminal, tells a stale binary from a server outage.
//!
//! The compiled half is generated by `build.rs` from cargo's own
//! `CARGO_FEATURE_*` exports and can never drift; `RELEASE_FEATURES` is the
//! one TYPED constant in this module and names what the public release
//! ships (`modelless` + `laya-riir` — the riir-owned comparison lane since
//! the candle removal, `.issues/006`; its weights do NOT ride the archive:
//! runtime HF download with SHA-256 pins, `src/laya/weights.rs`).

include!(concat!(env!("OUT_DIR"), "/features.rs"));

/// What the public release ships, sorted (the `gist-rs/reflex` release set).
pub const RELEASE_FEATURES: &[&str] = &["laya-riir", "modelless"];

/// Feature names in the compiled set that the release set requires and the
/// build lacks — empty on a complete release build.
pub fn missing() -> Vec<&'static str> {
    RELEASE_FEATURES
        .iter()
        .copied()
        .filter(|f| !COMPILED_FEATURES.contains(f))
        .collect()
}

/// The one-command rebuild that supplies everything [`missing`] names.
pub fn rebuild_command() -> String {
    "cargo build --profile dist --features laya-riir".to_string()
}

/// The full `--version` stamp: version line, compiled set, and — when the
/// set is incomplete against the release set — a `STALE` line naming the
/// gaps and the rebuild.
pub fn stamp() -> String {
    let mut s = format!("reflex {}\n", crate::VERSION);
    s.push_str(&format!(
        "compiled features: {}\n",
        COMPILED_FEATURES.join(" ")
    ));
    let missing = missing();
    if !missing.is_empty() {
        s.push_str(&format!(
            "release set: STALE — missing {}\nrebuild: {}\n",
            missing.join(" "),
            rebuild_command()
        ));
    }
    s
}
